set backspace=indent,eol,start
set cursorline
set encoding=utf-8
set fileencodings=utf-8,sjis,cp932,euc-jp,iso-2022-jp
set fileformats=unix,dos,mac
set hlsearch
set mouse=a
set number
set shiftwidth=4
set showmatch
set tabstop=4
