#!/bin/sh

cd $(cd $(dirname $0); pwd)

# Install Homebrew, Ansible and Python.
./install-ansible.sh

# Add this script to start-up.
path=$(cd $(dirname $0); pwd)/${0##*/}
tellto='tell application "System Events" to '
osa_args="{path:\"${path}\", hidden:false, name:\"${0##*/}\"}"
#osascript -e "${tellto}delete login item \"${0##*/}\""
osascript -e "${tellto}make login item at end with properties ${osa_args}"

ansible-playbook -i hosts --ask-pass --ask-sudo-pass -v playbook.yml
