#!/bin/sh

cd $(cd $(dirname $0); pwd)

echo 'Install Homebrew, Ansible and Python.'
./install-ansible.sh

echo 'Add this script to start-up.'
path=$(cd $(dirname $0); pwd)/${0##*/}
osa_args="{path:\"${path}\", hidden:false, name:\"${0##*/}\"}"
osascript -e "tell application \"System Events\" to make login item at end with properties ${osa_args}"

echo 'Enabling Remote login (SSH)'
sudo systemsetup -setremotelogin on
sudo dseditgroup -o create -q com.apple.access_ssh
sudo dseditgroup -o edit -a admin -t group com.apple.access_ssh

ansible-playbook -i hosts -v playbook.yml
