#!/bin/sh

reboot_flag='~/.reboot'
requested_reboot() {
    cmd="test -e ${reboot_flag} && echo -n 1 || echo -n 0"
    out=`vagrant ssh -c "${cmd}"`
    return $((out + 0))
}

cd $(cd $(dirname $0); pwd)
vagrant up --no-provision
vagrant rsync
vagrant provision

while :
do
    requested_reboot
    if [ $? -eq 0 ]
    then
        break
    fi
    vagrant ssh -c "rm -f ${reboot_flag}"
    vagrant rsync
    echo 'Reloading...'
    vagrant reload --provision
done
