---
- name: App Store / Check for software updates daily, not just once per week
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1

- name: App Store / Enable the automatic update check
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: true

- name: App Store / Enable the automatic security update check
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: bool
    value: true

- name: App Store / Download newly available updates in background
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: bool
    value: true

- name: App Store / Automatically download apps purchased on other Macs
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    type: bool
    value: true

- name: App Store / Turn on app auto-update
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: true

- name: App Store / Allow the App Store to reboot machine on macOS updates
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdateRestartRequired
    type: bool
    value: true
