---
- include: _defaults.yml
  with_items:
  - desc: App Store / Enable the automatic update check.
    path: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    value: -bool YES
    expect: 1
  - desc: App Store / Check for software updates daily, not just once per week.
    path: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    value: -int 1
    expect: 1
  - desc: App Store / Download newly available updates in background.
    path: com.apple.SoftwareUpdate
    key: AutomaticDownload
    value: -int 1
    expect: 1
  - desc: App Store / Automatically download apps purchased on other Macs.
    path: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    value: -int 1
    expect: 1
  - desc: App Store / Turn on app auto-update.
    path: com.apple.commerce
    key: AutoUpdate
    value: -bool YES
    expect: 1
  - desc: App Store / Allow the App Store to reboot machine on macOS updates.
    path: com.apple.commerce
    key: AutoUpdateRestartRequired
    value: -bool YES
    expect: 1

- include: _defaults.yml
  with_items:
  - desc: App Store / Disable the WebKit Developer Tools in the Mac App Store.
    path: com.apple.appstore
    key: WebKitDeveloperExtras
    value: -bool NO
    expect: 0
  - desc: App Store / Disable Debug Menu in the Mac App Store.
    path: com.apple.appstore
    key: ShowDebugMenu
    value: -bool NO
    expect: 0
