---
- name: International / Collect current locale.
  shell: defaults read NSGlobalDomain AppleLanguages
  register: locale
  changed_when: false

- name: International / Set languagesetup.
  shell: languagesetup -langspec "Japanese"
  become: true
  when: '"ja" not in locale.stdout'

- name: International / Set language
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
    - ja-JP

- name: International / Set locale
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    value: ja_JP

- name: International / Set measurement units
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    value: Centimeters

- name: International / Enable metric units
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true
