---
- name: Mail / Copy email addresses and name
  osx_defaults:
    domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: true

- name: Mail / Disable inline attachments (just show the icons)
  osx_defaults:
    domain: com.apple.mail
    key: DisableInlineAttachmentViewing
    type: bool
    value: true

- name: Activity Monitor / Show the main window when launched
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true

- name: Activity Monitor / Visualize CPU usage in the Dock icon
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 6

- name: Activity Monitor / Show all processes
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 100
