---
- name: Collect show the main window when launching Activity Monitor
  shell: defaults read com.apple.ActivityMonitor OpenMainWindow
  register: activity_open_window
  changed_when: false
  ignore_errors: true

- name: Show the main window when launching Activity Monitor
  shell: defaults write com.apple.ActivityMonitor OpenMainWindow -bool YES
  when: activity_open_window.stdout != "1"

- name: Collect show processes category in Activity Monitor
  shell: defaults read com.apple.ActivityMonitor ShowCategory
  register: activity_category
  changed_when: false
  ignore_errors: true

- name: Show all processes in Activity Monitor
  shell: defaults write com.apple.ActivityMonitor ShowCategory -int 100
  when: activity_category.stdout != "100"
