---
- include: _defaults.yml
  with_items:
  - desc: Show the main window when launching Activity Monitor.
    path: com.apple.ActivityMonitor
    key: OpenMainWindow
    value: -bool YES
    expect: 1
  - desc: Show all processes in Activity Monitor.
    path: com.apple.ActivityMonitor
    key: ShowCategory
    value: -int 100
    expect: 100
