---
- name: Screen / Require password after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1

- name: Screen / Require password after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 300

- name: Screen / Save screenshots format
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    value: png
  notify: Reload SystemUIServer

- name: Screen / Enable shadow in screenshots
  osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: false
  notify: Reload SystemUIServer

- name: Screen / Enable subpixel font rendering on non-Apple LCDs
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 3
