---
- name: 'Set settings: TextEdit / Use plain text mode for new documents '
  osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: bool
    value: false

- name: 'Set settings: TextEdit / Show page breaks'
  osx_defaults:
    domain: com.apple.TextEdit
    key: ShowPageBreaks
    type: bool
    value: true

- name: 'Set settings: TextEdit / Use check grammar with spelling'
  osx_defaults:
    domain: com.apple.TextEdit
    key: CheckGrammarWithSpelling
    type: bool
    value: true

- name: 'Set settings: TextEdit / View source at editing HTML'
  osx_defaults:
    domain: com.apple.TextEdit
    key: IgnoreHTML
    type: bool
    value: true

- name: 'Set settings: TextEdit / Save files as UTF-8'
  osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4

- name: 'Set settings: TextEdit / Use XHTML notation at output HTML'
  osx_defaults:
    domain: com.apple.TextEdit
    key: UseXHTMLDocType
    type: bool
    value: true

- name: 'Set settings: TextEdit / Use HTML transitional notation at output HTML'
  osx_defaults:
    domain: com.apple.TextEdit
    key: UseTransitionalDocType
    type: bool
    value: false
