---
- name: Install multi-media tools from Homebrew cask.
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
  - metasequoia
  - obs
  - adobe-creative-cloud

- name: Install multi-media tools from mas.
  shell: 'mas install {{ item }}'
  register: mas
  changed_when: '"already installed" in mas.stdout'
  with_items:
  - 408981434 #iMovie
  - 682658836 #GarageBand
