---
- name: Install Metasequoia from Homebrew cask.
  homebrew_cask:
    name: metasequoia
    state: present

- name: Install OBS from Homebrew cask.
  homebrew_cask:
    name: obs
    state: present

- name: Install Adobe Creative Cloud from Homebrew cask.
  homebrew_cask:
    name: adobe-creative-cloud
    state: present
