---
- name: Install .NET Framework from Homebrew cask.
  homebrew_cask:
    name: dotnet
    state: present

- name: Install Silverlight from Homebrew cask.
  homebrew_cask:
    name: silverlight
    state: present

- name: Install Java JRE from Homebrew cask.
  homebrew_cask:
    name: java
    state: present

- name: Install Adobe AIR from Homebrew cask.
  homebrew_cask:
    name: adobe-air
    state: present

- name: Install Flash Player Debugger from Homebrew cask.
  homebrew_cask:
    name: flash-player-debugger
    state: present

- name: Install Flash Player Debugger (PPAPI) from Homebrew cask.
  homebrew_cask:
    name: flash-player-debugger-ppapi
    state: present

- name: Install Flash Player Debugger (NPAPI) from Homebrew cask.
  homebrew_cask:
    name: flash-player-debugger-npapi
    state: present
