---
- name: Install runtime tools from Homebrew.
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
  - mono

- name: Install Silverlight from Homebrew cask.
  homebrew_cask:
    name: silverlight
    state: present

- name: Install Java JRE from Homebrew cask.
  homebrew_cask:
    name: java
    state: present

- name: Install Adobe AIR from Homebrew cask.
  homebrew_cask:
    name: adobe-air
    state: present

- name: Install Flash Player Debugger from Homebrew cask.
  homebrew_cask:
    name: flash-player-debugger
    state: present

- name: Install Flash Player Debugger (PPAPI) from Homebrew cask.
  homebrew_cask:
    name: flash-player-debugger-ppapi
    state: present

- name: Install Flash Player Debugger (NPAPI) from Homebrew cask.
  homebrew_cask:
    name: flash-player-debugger-npapi
    state: present

- name: Install Unity Web player from Homebrew cask.
  homebrew_cask:
    name: unity-web-player
    state: present
