---
- name: Install runtimes from Homebrew cask.
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
  - dotnet
  - silverlight
  - java
  #- adobe-air # Too heavy.
  - flash-player-debugger
  - flash-player-debugger-ppapi
  - flash-player-debugger-npapi
