---
- name: Install runtime tools from Homebrew.
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
  - mono

- name: Install Flash Player from Homebrew cask.
  homebrew_cask:
    name: flash-npapi
    state: present

- name: Install Java JRE from Homebrew cask.
  homebrew_cask:
    name: java
    state: present

# ### Because it is risk to freeze, it is deleted temporary. ###
# - name: Install Adobe AIR from Homebrew cask.
#   homebrew_cask:
#     name: adobe-air
#     state: present

- name: Install Unity Web player from Homebrew cask.
  homebrew_cask:
    name: unity-web-player
    state: present
