---
- name: Install runtimes from Homebrew cask.
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
  - dotnet
  - silverlight
  - java
  - adobe-air
  - flash-player-debugger
  - flash-player-debugger-ppapi
  - flash-player-debugger-npapi
