---
- name: Install utility tools from Homebrew.
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
  - gpg
  - openssh
  - p7zip
  - rename
  - sl
  - wget
  - xz

- name: Install mas.
  homebrew:
    name: mas
    state: latest

- name: Install brew cu updater.
  homebrew_tap:
    name: buo/cask-upgrade
