---
- name: Install utility tools from Homebrew.
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items:
  - gpg
  - openssh
  - sl
  - wget
  - xz
  - p7zip

# brew tap buo/cask-upgrade

- name: Install Drobo dashboard from Homebrew cask.
  homebrew_cask:
    name: drobo-dashboard
    state: present
