---
- name: Collect current timezone
  shell: systemsetup -gettimezone
  become: true
  changed_when: false
  register: timezone

- name: Change current timezone Asia/Tokyo
  shell: systemsetup -settimezone 'Asia/Tokyo'
  become: true
  when: '"Asia/Tokyo" not in timezone.stdout'
  notify: Reboot macOS
